import os
import sipconfig
from PyQt5 import QtCore
sip_inc_dir = "/usr/share/python3-sip/PyQt5" # Fedora
sip_inc_dir = "/usr/share/sip/PyQt5" # ArchLinux

basename = "designer"

# The name of the SIP build file generated by SIP and used by the build system.
build_file = basename + ".sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file,
                    "-I" + sip_inc_dir,
                    QtCore.PYQT_CONFIGURATION["sip_flags"],
                    basename + ".sip"]))

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# makefile.extra_include_dirs = [ "/usr/include/qt5",
#                                 "/usr/include/qt5/QtCore",
#                                 "/usr/include/qt5/QtGui",
#                                 "/usr/include/qt5/QtWidgets",
#                                 "/usr/include/qt5/QtDesigner"
#                                 ]

# makefile.extra_libs = ["Qt5Widgets", "Qt5Gui", "Qt5Core", "Qt5Designer", "Qt5DesignerComponents" ]

cflags = os.popen ("pkg-config Qt5Core Qt5Designer --cflags").read()
libs = os.popen ("pkg-config Qt5Core Qt5Designer --libs").read()

makefile.extra_cxxflags = cflags.split ()
makefile.extra_lflags = libs.split ()
makefile.extra_libs = [ "Qt5DesignerComponents" ]

# Generate the Makefile itself.
makefile.generate()

# dnf install python3-sip-devel
# dnf install python3-qt5-devel

# /usr/lib/python3.6/site-packages/sipconfig.py
# /usr/include/qt5
# /usr/share/python3-sip/PyQt5

# pacman -S sip
# pacman -S python-sip

# https://github.com/zanton/hello-sip-pyqt5

